executors:
  main:
    docker:
      - image: circleci/golang
    working_directory: /go/src/github.com/elimity-com/scim

jobs:
  lint:
    executor: main
    steps:
      - checkout
      - run: curl -sfL https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | sh -s v1.19.0
      - run: ./bin/golangci-lint -E goimports,golint --exclude-use-default=false run
  test:
    executor: main
    environment:
      TEST_RESULTS_DIR: /tmp/test-results/go-test
    steps:
      - checkout
      - run: mkdir -p $TEST_RESULTS_DIR
      - run: go get github.com/jstemmer/go-junit-report
      - run: go test -v | go-junit-report > ${TEST_RESULTS_DIR}/results.xml
      - store_artifacts:
          path: /tmp/test-results
      - store_test_results:
          path: /tmp/test-results

version: 2.1

workflows:
  main:
    jobs:
      - lint
      - test
  version: 2
